"use client";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { signIn } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import { BookHeart, ArrowRight, Moon } from "lucide-react";
import AmbientBackground from "../app/AmbientBackground";

export default function LandingPage({ onOpenApp }: { onOpenApp: () => void }) {
  const [waitlistOpen, setWaitlistOpen] = useState(false);
  const [authOpen, setAuthOpen] = useState(false);
  const [authMode, setAuthMode] = useState<"signin" | "signup">("signup");
  useEffect(() => { try { const p = new URLSearchParams(window.location.search); if (p.get("ebook") === "success") { toast.success("Your ebook is on the way!"); const u = new URL(window.location.href); u.searchParams.delete("ebook"); window.history.replaceState({}, "", u.toString()); } } catch {} }, []);
  const openAuth = (m: "signin" | "signup" = "signup") => { setAuthMode(m); setAuthOpen(true); };
  const sage = "linear-gradient(135deg, #4A5D53, #2C3E36)";

  return (
    <div className="relative min-h-screen overflow-hidden" style={{ background: "#F9F7F4" }}>
      <AmbientBackground />
      {/* Nav */}
      <nav className="relative z-30 flex items-center justify-between px-6 md:px-16 py-7">
        <div className="flex items-center gap-3">
          <svg viewBox="0 0 48 48" fill="none" className="w-12 h-12 flex-none"><circle cx="24" cy="24" r="22" stroke="#C6A15B" strokeWidth="1" /><circle cx="24" cy="24" r="17" stroke="#C6A15B" strokeWidth="0.8" strokeDasharray="2 2" /><path d="M24 13c-3.5 5-7 9-7 14a7 7 0 0 0 14 0c0-5-3.5-9-7-14z" fill="#4A5D53" fillOpacity="0.9" /></svg>
          <div><div style={{ fontFamily: "var(--font-parisienne)" }} className="text-2xl leading-none text-sage-deep">Tender Trimesters</div><div className="text-[8px] tracking-[0.3em] text-gold mt-1 font-medium">PREGNANCY &amp; BEYOND</div></div>
        </div>
        <div className="hidden md:flex items-center gap-8 text-[13px] tracking-[0.14em] font-medium text-cocoa-soft"><a href="#signature" className="hover:text-sage-deep transition-colors">Keepsakes</a><a href="#bundle" className="hover:text-sage-deep transition-colors">Bundle</a></div>
        <button onClick={() => openAuth("signin")} className="hidden sm:inline-flex text-[14px]" text-cocoa hover:text-sage-deep transition-colors font-medium tracking-wide">Sign in</button>
        <button onClick={() => openAuth("signup")} className="inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-[13px] tracking-[0.1em] font-medium text-cream transition-transform hover:scale-105" style={{ background: sage, boxShadow: "0 8px 24px rgba(74,93,83,0.25)" }}>Open the App<ArrowRight className="w-3.5 h-3.5" /></button>
      </nav>
      {/* Hero */}
      <div className="relative z-20 grid md:grid-cols-[1.1fr_0.9fr] items-center gap-8 px-6 md:px-16 py-12 md:py-20 max-w-[1200px] mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1.2 }}>
          <div className="eyebrow mb-8">Your 24/7 pregnancy companion</div>
          <h1 style={{ fontFamily: "var(--font-cormorant)", fontWeight: 600, fontSize: "clamp(40px, 5vw, 68px)", lineHeight: 1.05, color: "#2C3E36" }} className="mb-6">Your pregnancy, <span style={{ fontFamily: "var(--font-parisienne)", fontWeight: 400, color: "#C9827C", fontSize: "1.2em", display: "inline-block", transform: "translateY(3px)" }}>one week</span> at a time.</h1>
          <p className="text-[16px] font-light leading-[1.8] text-cocoa-soft max-w-[48ch] mb-10">A nurturing weekly calendar, daily tender notes, a private journal, and Tempie — your AI companion who's there at 3am when you need her most. Built with love by Helena-Ann Baker.</p>
          <div className="flex gap-3 mb-8 flex-wrap">
            <button onClick={() => openAuth("signup")} className="inline-flex items-center gap-2.5 rounded-full px-8 py-3.5 text-[14px]" tracking-[0.1em] font-medium text-cream transition-transform hover:scale-105" style={{ background: sage, boxShadow: "0 8px 24px rgba(74,93,83,0.25)" }}>Begin your 40 weeks<ArrowRight className="w-4 h-4" /></button>
            <button onClick={() => setWaitlistOpen(true)} className="inline-flex items-center gap-2.5 rounded-full px-7 py-3.5 text-[14px]" tracking-[0.1em] font-medium text-sage-deep transition-colors hover:bg-white" style={{ border: "1px solid #C6A15B", background: "rgba(255,255,255,0.5)" }}>Join the waitlist</button>
          </div>
          <div className="flex items-center gap-3 text-[12px] tracking-[0.12em] text-cocoa-soft"><span className="text-gold tracking-[3px] text-[14px]"">{"★★★★★"}</span><span>Free forever · Private &amp; secure · 40 weeks of content</span></div>
        </motion.div>
        {/* Phone mockup */}
        <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.2, delay: 0.3 }} className="relative flex justify-center min-h-[480px]">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full" style={{ width: "min(440px,85%)", aspectRatio: "1", border: "1px solid rgba(198,161,91,0.25)" }}><div className="absolute inset-4 rounded-full" style={{ border: "1px dashed rgba(198,161,91,0.2)" }} /></div>
          <div className="absolute z-30 animate-bob flex items-center gap-2 rounded-xl px-3.5 py-2 text-[9px] tracking-[0.14em] font-medium uppercase" style={{ top: 30, left: -10, background: "rgba(255,254,252,0.95)", border: "1px solid #E5E0D8", boxShadow: "0 10px 28px rgba(74,93,83,0.12)" }}><svg width="10" height="10" viewBox="0 0 12 12"><path d="M6 0l1.3 4.7L12 6 7.3 7.3 6 12 4.7 7.3 0 6l4.7-1.3z" fill="#C6A15B" /></svg><span style={{ color: "#C6A15B" }}>Week 20 · 60%</span></div>
          <div className="absolute z-30 animate-bob flex items-center gap-2 rounded-xl px-3.5 py-2 text-[9px] tracking-[0.14em] font-medium uppercase" style={{ bottom: 60, right: -10, animationDelay: "1.5s", background: "rgba(255,254,252,0.95)", border: "1px solid #E5E0D8", boxShadow: "0 10px 28px rgba(74,93,83,0.12)" }}><svg width="10" height="10" viewBox="0 0 24 24" fill="#4A5D53"><path d="M12 21s-8-5.3-8-11a4.6 4.6 0 0 1 8-3 4.6 4.6 0 0 1 8 3c0 5.7-8 11-8 11z" /></svg><span style={{ color: "#4A5D53" }}>Tempie · 24/7</span></div>
          {/* Phone */}
          <div className="relative z-20 animate-glow-pulse" style={{ width: "30em", height: "66em", borderRadius: "4.4em", background: "#3A3530", padding: "0.5em", fontSize: "7.5px", boxShadow: "0 28px 60px rgba(74,93,83,0.25)" }}>
            <div className="relative w-full h-full flex flex-col overflow-hidden" style={{ borderRadius: "3.8em", background: "linear-gradient(180deg, #FFFEFC 0%, #F5F0EB 100%)" }}>
              <div className="absolute top-[0.8em] left-1/2 -translate-x-1/2 z-9" style={{ width: "9em", height: "2em", background: "#3A3530", borderRadius: "1em" }} />
              <div className="flex justify-between items-center pt-[1em] px-[1.7em]" style={{ fontSize: "1.05em", fontWeight: 500, color: "#4A4038" }}><span>9:41</span><div className="flex gap-[0.25em] items-end">{[0.4,0.58,0.76,0.94].map((h,i)=><span key={i} style={{ width: "0.3em", height: `${h}em`, background: "#4A4038", borderRadius: "0.1em" }} />)}</div></div>
              <div className="flex-1 min-h-0 px-[1.3em] pt-[0.8em] pb-[6em] flex flex-col gap-[0.9em] overflow-hidden">
                <div className="flex justify-between items-center"><div><div style={{ fontSize: "0.85em", letterSpacing: "0.28em", color: "#C6A15B", fontWeight: 600 }}>GOOD MORNING</div><div style={{ fontFamily: "var(--font-cormorant)", fontSize: "2.1em", fontWeight: 600, color: "#2C3E36", lineHeight: 1.1, marginTop: "0.15em" }}>Hello, <span style={{ fontFamily: "var(--font-parisienne)", color: "#C9827C", fontWeight: 400, fontSize: "1.2em" }}>Mama</span></div></div><div style={{ width: "3.5em", height: "3.5em", borderRadius: "50%", overflow: "hidden", boxShadow: "0 0 0 0.2em #fff, 0 0 0 0.35em #E7D3A8" }}><svg viewBox="0 0 40 40"><circle cx="20" cy="20" r="20" fill="#F2E6E4" /><circle cx="20" cy="16" r="5.5" fill="#4A5D53" /><path d="M8 38c0-5.5 4.5-9.5 12-9.5s12 4 12 9.5" fill="#4A5D53" /></svg></div></div>
                <div className="bg-white flex items-center gap-[1.2em]" style={{ borderRadius: "1.5em", boxShadow: "0 0.8em 2em rgba(74,93,83,0.08)", padding: "1.1em 1.25em" }}><div className="relative flex-none" style={{ width: "6.5em", height: "6.5em" }}><svg viewBox="0 0 48 48" className="w-full h-full -rotate-90 block"><circle cx="24" cy="24" r="20" fill="none" stroke="#EDE8E0" strokeWidth="5" /><circle cx="24" cy="24" r="20" fill="none" stroke="#C6A15B" strokeWidth="5" strokeLinecap="round" strokeDasharray="113.1 188.5" /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><b style={{ fontFamily: "var(--font-cormorant)", fontSize: "1.8em", color: "#2C3E36", fontWeight: 600 }}>20</b><span style={{ fontSize: "0.55em", letterSpacing: "0.24em", color: "#8A7E72", fontWeight: 600 }}>WEEKS</span></div></div><div><span className="inline-block" style={{ background: "#EDEFF0", color: "#4A5D53", borderRadius: "99em", padding: "0.35em 0.85em", fontSize: "0.65em", letterSpacing: "0.2em", fontWeight: 600 }}>SECOND TRIMESTER</span><h4 style={{ fontFamily: "var(--font-cormorant)", fontSize: "1.4em", fontWeight: 600, color: "#2C3E36", margin: "0.45em 0 0.25em", lineHeight: 1.15 }}>Your baby is about the size of a mango</h4><p style={{ fontSize: "1em", color: "#8A7E72", fontWeight: 300, lineHeight: 1.4 }}>116 days to go — you're 60% there.</p></div></div>
                <div style={{ background: "linear-gradient(135deg, #F8F0EE, #F2E6E4)", borderRadius: "1.5em", boxShadow: "0 0.8em 2em rgba(74,93,83,0.08)", padding: "1.1em 1.25em", borderLeft: "0.3em solid #C6A15B" }}><span style={{ fontSize: "0.65em", letterSpacing: "0.28em", color: "#4A5D53", fontWeight: 600, display: "flex", alignItems: "center", gap: "0.5em", textTransform: "uppercase" }}><svg width="10" height="10" viewBox="0 0 12 12"><path d="M6 0l1.3 4.7L12 6 7.3 7.3 6 12 4.7 7.3 0 6l4.7-1.3z" fill="#C6A15B" /></svg>Today's tender note</span><p style={{ fontFamily: "var(--font-cormorant)", fontStyle: "italic", fontSize: "1.35em", color: "#2C3E36", lineHeight: 1.3, margin: "0.5em 0 0.45em" }}>"You are growing a whole person, Mama — and becoming one yourself."</p><span style={{ fontFamily: "var(--font-parisienne)", color: "#C9827C", fontSize: "1.1em" }}>— from one mama's heart to yours</span></div>
                <div style={{ fontSize: "0.7em", letterSpacing: "0.26em", fontWeight: 600, textTransform: "uppercase", color: "#4A5D53", display: "flex", alignItems: "baseline", gap: "0.45em" }}>Your Journey<small style={{ letterSpacing: "0.08em", color: "#8A7E72", fontWeight: 400, fontSize: "1em", textTransform: "none" }}>· the four pillars</small></div>
                <div className="grid grid-cols-2 gap-[0.85em]">{[{l:"Pregnancy & Birth",s:"Week-by-week"},{l:"Feeding & Newborn",s:"Bottles & latch"},{l:"Sleep & Wellness",s:"Rest for two"},{l:"Postpartum",s:"Healing & thriving"}].map((t,i)=>(<button key={i} className="bg-white text-left flex flex-col gap-[0.4em] cursor-pointer transition-transform hover:scale-[1.02]" style={{ border: "1px solid #EDE8E0", borderRadius: "1.4em", padding: "0.85em 0.9em", boxShadow: "0 0.6em 1.4em rgba(74,93,83,0.06)", color: "#4A4038" }}><span style={{ width: "2.3em", height: "2.3em", borderRadius: "50%", background: "#F2E6E4", display: "flex", alignItems: "center", justifyContent: "center" }}><svg width="1.3em" height="1.3em" viewBox="0 0 24 24" fill="none" stroke="#4A5D53" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{i===0&&<path d="M12 20s-7.5-4.8-7.5-10.2A4.3 4.3 0 0 1 12 7a4.3 4.3 0 0 1 7.5 2.8C19.5 15.2 12 20 12 20z"/>}{i===1&&<><rect x="10" y="8" width="4" height="9" rx="1.5"/><path d="M10.5 8V6.5h3V8"/></>}{i===2&&<path d="M19.5 14.2A8 8 0 1 1 9.8 4.5a6.4 6.4 0 0 0 9.7 9.7z"/>}{i===3&&<><path d="M12 20.5v-8"/><path d="M12 12.5C12 8 8.8 5.5 5 5.5c0 4.3 3 6.8 7 7z"/></>}</svg></span><b style={{ fontSize: "1em", fontWeight: 600, color: "#2C3E36" }}>{t.l}</b><small style={{ fontSize: "0.85em", color: "#8A7E72", fontWeight: 300 }}>{t.s}</small></button>))}</div>
                <div className="flex items-center justify-between gap-[1em]" style={{ background: "linear-gradient(135deg, #4A5D53, #2C3E36)", borderRadius: "1.5em", padding: "1em 1.25em", boxShadow: "0 0.8em 2em rgba(74,93,83,0.2)" }}><div style={{ color: "#F9F7F4" }}><b style={{ fontFamily: "var(--font-cormorant)", fontSize: "1.4em", fontWeight: 600 }}>You're not alone.</b><small style={{ display: "block", fontSize: "0.85em", opacity: 0.8, fontWeight: 300, marginTop: "0.1em" }}>2,438 mamas in the Circle</small></div><span style={{ background: "#F9F7F4", color: "#4A5D53", borderRadius: "99em", padding: "0.55em 1.2em", fontSize: "0.8em", fontWeight: 600, whiteSpace: "nowrap" }}>Join</span></div>
              </div>
              <nav className="absolute left-0 right-0 bottom-0 flex items-center justify-around px-[0.5em] z-8" style={{ height: "5.5em", background: "rgba(255,254,252,0.95)", borderTop: "1px solid #E5E0D8" }}>{[{l:"Home",p:<path d="M4 11.2 12 4.5l8 6.7V20h-5.4v-5.2h-5.2V20H4z"/>,a:true},{l:"Journal",p:<rect x="5.5" y="3.5" width="13" height="17" rx="2"/>,a:false},{l:"Circle",p:<path d="M12 4c-4.6 0-8.3 3.2-8.3 7.2 0 2.2 1.1 4.1 2.8 5.4L5 20.5l3.9-1.6c1 .3 2 .5 3.1.5 4.6 0 8.3-3.2 8.3-7.2S16.6 4 12 4z"/>,a:false},{l:"Book",p:<path d="M12 6.5C10 4.8 7 4.5 4.5 4.8v13.4c2.5-.3 5.5 0 7.5 1.7 2-1.7 5-2 7.5-1.7V4.8C17 4.5 14 4.8 12 6.5z"/>,a:false},{l:"You",p:<><circle cx="12" cy="8" r="3.6"/><path d="M5 20c.8-3.6 3.8-5.2 7-5.2s6.2 1.6 7 5.2"/></>,a:false}].map((n,i)=>(<span key={n.l} className={`flex flex-col items-center gap-[0.25em] ${n.a?"text-sage-deep":"text-cocoa-soft"}`} style={{ fontSize: "0.65em", letterSpacing: "0.08em", fontWeight: 500 }}><svg width="1.7em" height="1.7em" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{n.p}</svg>{n.l}{n.a&&<span style={{ width: "0.35em", height: "0.35em", background: "#C6A15B", borderRadius: "50%" }} />}</span>))}</nav>
            </div>
          </div>
        </motion.div>
      </div>
      {/* Ribbon */}
      <div className="relative z-20 flex items-center gap-6 justify-center px-8 py-6"><div className="h-px flex-1 max-w-[180px]" style={{ background: "linear-gradient(90deg, transparent, #C6A15B)" }} /><span className="text-[10px] tracking-[0.4em] text-gold font-medium whitespace-nowrap">FREE FOREVER · PRIVATE · 40 WEEKS · TEMPIE 24/7</span><div className="h-px flex-1 max-w-[180px]" style={{ background: "linear-gradient(90deg, #C6A15B, transparent)" }} /></div>
      {/* Pricing */}
      <section id="comparison" className="py-20 md:py-28 px-6"><div className="max-w-2xl mx-auto text-center"><div className="eyebrow mb-6">Choose your journey</div><p style={{ fontFamily: "var(--font-cormorant)" }} className="text-3xl md:text-4xl leading-tight text-sage-ink"><span className="text-cocoa-soft">Free,</span> <span style={{ fontFamily: "var(--font-parisienne)" }} className="text-rose text-4xl">forever.</span><br /><span className="text-cocoa-soft">When you're ready to be fully held,</span><br /><span className="shimmer-text">$9.99 once.</span></p><div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"><button onClick={() => openAuth("signup")} className="inline-flex items-center gap-2.5 rounded-full px-8 h-12 text-[14px]" tracking-wide font-medium text-cream transition-transform hover:scale-105" style={{ background: sage, boxShadow: "0 8px 24px rgba(74,93,83,0.25)" }}>Begin free<ArrowRight className="w-4 h-4" /></button><span className="text-[13px] text-cocoa-soft tracking-wide">or $4.99/month</span></div></div></section>
      {/* Signature Features */}
      <section id="signature" className="py-20 md:py-28 px-6" style={{ background: "rgba(242,230,228,0.25)" }}><div className="max-w-5xl mx-auto"><div className="text-center mb-14"><div className="eyebrow mb-3">Nine keepsakes you won't find anywhere else</div><h2 style={{ fontFamily: "var(--font-cormorant)" }} className="text-3xl md:text-4xl text-sage-ink">The sanctuary within.</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{[{t:"Letters from Baby",d:"Each week your baby writes you a tender letter in their own voice."},{t:"Fear to Flame",d:"Name a fear. Watch AI gently reframe it into courage."},{t:"My Mother's Mother",d:"12 guided interview prompts that capture a generational keepsake."},{t:"DreamKeeper",d:"Log your vivid pregnancy dreams. AI surfaces recurring symbols."},{t:"Hormone Horoscope",d:"A poetic, science-backed forecast of what your hormones are doing."},{t:"The Name Garden",d:"Plant name ideas as seeds. Watch them grow."},{t:"Memory Capsule",d:"Seal letters and promises that unlock for your child on a future date."},{t:"Birth Playlist Composer",d:"Build the soundtrack for labor by phase."},{t:"Belly Bonding Rituals",d:"A daily 60-second ritual — a phrase, a hand position, a breath."}].map((f,i)=>(<motion.div key={f.t} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.05 }}><div className="bg-white rounded-2xl p-6 h-full transition-all hover:scale-[1.02] hover:shadow-md" style={{ border: "1px solid #EDE8E0" }}><div className="w-9 h-9 rounded-full mb-3 flex items-center justify-center" style={{ background: "#F2E6E4" }}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#4A5D53" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" /></svg></div><h3 style={{ fontFamily: "var(--font-cormorant)" }} className="text-lg text-sage-ink mb-1.5 font-semibold">{f.t}</h3><p className="text-[14px]" text-cocoa-soft leading-relaxed">{f.d}</p></div></motion.div>))}</div></div></section>
      {/* Quote */}
      <section className="relative py-24 md:py-32 overflow-hidden" style={{ background: "linear-gradient(165deg, #2C3E36, #4A5D53)" }}><div className="absolute inset-0 opacity-15"><div className="absolute top-1/4 left-1/4 w-80 h-80 rounded-full blur-3xl opacity-50 animate-breathe" style={{ background: "#C6A15B" }} /></div><div className="max-w-3xl mx-auto px-6 text-center relative z-10"><Moon className="w-10 h-10 text-gold mx-auto mb-6 animate-breathe" /><p style={{ fontFamily: "var(--font-cormorant)" }} className="text-3xl md:text-4xl text-cream leading-tight"><span style={{ fontStyle: "italic" }}>She is becoming a mother.</span><br /><span className="text-gold">We are keeping every week.</span></p></div></section>
      {/* Testimonials */}
      <section id="testimonials" className="py-20 md:py-28 px-6"><div className="max-w-5xl mx-auto"><div className="mb-12"><div className="eyebrow mb-3">Mama stories</div><h2 style={{ fontFamily: "var(--font-cormorant)" }} className="text-3xl md:text-4xl text-sage-ink">You are not alone in this.</h2></div><div className="grid md:grid-cols-3 gap-5">{[{t:"It feels like a friend is checking in with me. The weekly tips feel personal.",n:"First-time mom",d:"Week 22"},{t:"Tempie answered my 3am panic about whether my baby's kicks were normal.",n:"Mama of one",d:"Week 28"},{t:"I cried when I read the affirmation on week 16. I needed that.",n:"Tender Trimesters mama",d:"Week 16"}].map((q,i)=>(<motion.div key={i} initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }}><Card className="rounded-2xl p-7 h-full relative overflow-hidden" style={{ background: "#FFFEFC", border: "1px solid #EDE8E0" }}><div style={{ fontFamily: "var(--font-parisienne)" }} className="text-6xl text-rose/10 absolute top-1 left-3 leading-none">{"\""}</div><div className="relative z-10"><p style={{ fontFamily: "var(--font-cormorant)", fontStyle: "italic" }} className="text-[17px] text-cocoa leading-relaxed mb-5">{q.t}</p><div className="pt-3 border-t" style={{ borderColor: "rgba(74,93,83,0.08)" }}><div style={{ fontFamily: "var(--font-parisienne)" }} className="text-xl text-rose leading-none">{q.n}</div><div className="eyebrow text-cocoa-soft mt-1.5">{q.d}</div></div></div></Card></motion.div>))}</div></div></section>
      {/* Bundle */}
      <section id="bundle" className="py-20 md:py-28 px-6"><div className="max-w-5xl mx-auto"><Card className="overflow-hidden" style={{ background: "linear-gradient(135deg, #2C3E36, #4A5D53)", border: "1px solid rgba(198,161,91,0.15)" }}><div className="p-8 md:p-12 text-cream"><div className="mb-10"><div className="eyebrow text-gold mb-4">Premium Bundle</div><h2 style={{ fontFamily: "var(--font-cormorant)" }} className="text-3xl md:text-4xl">Everything mama needs, in one place.</h2></div><div className="grid sm:grid-cols-2 gap-3 mb-10">{[{t:"Mommies Matter Ebook",d:"17 chapters covering epidural decisions, feeding, NICU, postpartum healing."},{t:"Affirmation Card Deck",d:"40 printable cards — one per week."},{t:"First-Trimester Checklist",d:"The survival guide for weeks 1-13."},{t:"Letters to Baby Templates",d:"Writing prompts for each trimester."}].map((item)=>(<div key={item.t} className="rounded-xl p-5 flex gap-3" style={{ background: "rgba(255,255,255,0.06)", border: "1px solid rgba(198,161,91,0.1)" }}><div className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0" style={{ background: "rgba(198,161,91,0.12)" }}><BookHeart className="w-4 h-4 text-gold" /></div><div><div style={{ fontFamily: "var(--font-cormorant)" }} className="text-lg text-cream">{item.t}</div><div className="text-[14px]" text-cream/60 mt-0.5 leading-relaxed">{item.d}</div></div></div>))}</div><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-5 pt-6 border-t" style={{ borderColor: "rgba(198,161,91,0.1)" }}><div className="flex items-baseline gap-2.5"><span className="text-cream/30 line-through text-base">$29.99</span><span style={{ fontFamily: "var(--font-cormorant)" }} className="text-5xl text-gold">$9.99</span><span className="text-cream/50 text-[14px]"">one-time</span></div><button onClick={() => openAuth("signup")} className="inline-flex items-center gap-2.5 rounded-full px-8 h-12 text-[14px]" tracking-wide font-medium transition-transform hover:scale-105" style={{ background: "#C6A15B", color: "#2C3E36" }}>Get the Bundle<ArrowRight className="w-4 h-4" /></button></div></div></Card></div></section>
      {/* Waitlist CTA */}
      <section className="py-24 md:py-32 px-6 relative overflow-hidden" style={{ background: "linear-gradient(165deg, #F8F0EE, #F2E6E4)" }}><div className="absolute top-1/4 right-1/4 w-80 h-80 rounded-full blur-3xl opacity-15 animate-breathe" style={{ background: "#C6A15B" }} /><div className="max-w-2xl mx-auto text-center relative z-10"><Moon className="w-12 h-12 text-gold mx-auto mb-6 animate-breathe" /><h2 style={{ fontFamily: "var(--font-cormorant)" }} className="text-3xl md:text-4xl text-sage-ink leading-tight mb-4">The waitlist is open.<br /><span style={{ fontFamily: "var(--font-parisienne)" }} className="text-rose text-4xl">Be the first to hold this.</span></h2><p className="text-cocoa-soft text-[17px] leading-relaxed max-w-md mx-auto mb-8">Join 200+ mamas getting early access, free affirmation drops, and Helena-Ann's letters from the journey.</p><button onClick={() => setWaitlistOpen(true)} className="inline-flex items-center gap-2.5 rounded-full px-8 h-12 text-[14px]" tracking-wide font-medium text-cream transition-transform hover:scale-105" style={{ background: sage, boxShadow: "0 8px 24px rgba(74,93,83,0.25)" }}>Join the Waitlist<ArrowRight className="w-4 h-4" /></button></div></section>
      {/* Footer */}
      <footer className="py-14 px-6" style={{ background: "#2C3E36" }}><div className="max-w-6xl mx-auto grid md:grid-cols-4 gap-8"><div className="md:col-span-2"><div className="flex items-center gap-2.5 mb-4"><svg viewBox="0 0 48 48" fill="none" className="w-9 h-9"><circle cx="24" cy="24" r="22" stroke="#C6A15B" strokeWidth="1" /><path d="M24 13c-3.5 5-7 9-7 14a7 7 0 0 0 14 0c0-5-3.5-9-7-14z" fill="#4A5D53" /></svg><div><div style={{ fontFamily: "var(--font-parisienne)" }} className="text-xl text-cream">Tender Trimesters</div><div className="text-[8px] tracking-[0.3em] text-gold mt-0.5">PREGNANCY &amp; BEYOND</div></div></div><p className="text-[14px]" text-cream/50 leading-relaxed max-w-md">Built with love by Helena-Ann Baker — mama, author, and your companion on this journey.</p></div><div><div className="eyebrow text-cream mb-3">The App</div><ul className="space-y-2 text-[14px]" text-cream/60"><li><a href="#signature" className="hover:text-gold transition-colors">Features</a></li><li><a href="#comparison" className="hover:text-gold transition-colors">Pricing</a></li><li><a href="#bundle" className="hover:text-gold transition-colors">Bundle</a></li></ul></div><div><div className="eyebrow text-cream mb-3">About</div><ul className="space-y-2 text-[14px]" text-cream/60"><li><a href="#testimonials" className="hover:text-gold transition-colors">Stories</a></li><li><a href="mailto:hello@mommiesmatter.com" className="hover:text-gold transition-colors">Contact</a></li><li><a href="/privacy" className="hover:text-gold transition-colors">Privacy</a></li><li><a href="/terms" className="hover:text-gold transition-colors">Terms</a></li></ul></div></div><div className="max-w-6xl mx-auto mt-10 pt-5 flex flex-col sm:flex-row justify-between items-center gap-3 text-[12px] text-cream/40" style={{ borderTop: "1px solid rgba(198,161,91,0.1)" }}><div>&copy; {new Date().getFullYear()} Mommies Matter. All rights reserved.</div><div style={{ fontFamily: "var(--font-parisienne)" }} className="text-rose text-base">made with love, mama</div></div></footer>
      <WaitlistDialog open={waitlistOpen} onOpenChange={setWaitlistOpen} />
      <AuthDialog open={authOpen} onOpenChange={setAuthOpen} mode={authMode} setMode={setAuthMode} onSuccess={onOpenApp} />
    </div>
  );
}

function WaitlistDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (v: boolean) => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [loading, setLoading] = useState(false); const [done, setDone] = useState(false);
  async function submit() { if (!email || !email.includes("@")) { toast.error("Please enter a valid email"); return; } setLoading(true); try { const res = await fetch("/api/waitlist", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, name, source: "landing_dialog" }) }); if (!res.ok) throw new Error(); setDone(true); toast.success("You're on the list, mama"); } catch { toast.error("Something went wrong."); } finally { setLoading(false); } }
  return (<Dialog open={open} onOpenChange={(v) => { onOpenChange(v); if (!v) setTimeout(() => { setDone(false); setName(""); setEmail(""); }, 300); }}><DialogContent className="rounded-2xl max-w-md" style={{ background: "#FFFEFC", border: "1px solid #E5E0D8" }}>{done ? (<div className="text-center py-8"><div className="w-14 h-14 rounded-full mx-auto flex items-center justify-center mb-4 animate-breathe" style={{ background: "#F2E6E4" }}><svg width="24" height="24" viewBox="0 0 24 24" fill="#4A5D53"><path d="M12 21s-8-5.3-8-11a4.6 4.6 0 0 1 8-3 4.6 4.6 0 0 1 8 3c0 5.7-8 11-8 11z" /></svg></div><h3 style={{ fontFamily: "var(--font-cormorant)" }} className="text-2xl text-sage-deep mb-2">Welcome, mama.</h3><p className="text-[14px]" text-cocoa-soft">You're on the list. Watch your inbox.</p></div>) : (<><DialogHeader><DialogTitle style={{ fontFamily: "var(--font-cormorant)" }} className="text-xl text-sage-deep">Join the waitlist</DialogTitle><DialogDescription>Be first to know when premium drops.</DialogDescription></DialogHeader><div className="space-y-3 mt-2"><div><Label htmlFor="wl-name">Name (optional)</Label><Input id="wl-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Mama" className="mt-1 rounded-lg" /></div><div><Label htmlFor="wl-email">Email</Label><Input id="wl-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@email.com" className="mt-1 rounded-lg" /></div><Button onClick={submit} disabled={loading} className="w-full rounded-full h-10 text-cream" style={{ background: "linear-gradient(135deg, #4A5D53, #2C3E36)" }}>{loading ? "Adding you..." : "Join the waitlist"}</Button><p className="text-[12px] text-cocoa-soft text-center">No spam. Just mama things.</p></div></>)}</DialogContent></Dialog>);
}

function AuthDialog({ open, onOpenChange, mode, setMode, onSuccess }: { open: boolean; onOpenChange: (v: boolean) => void; mode: "signin" | "signup"; setMode: (m: "signin" | "signup") => void; onSuccess: () => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit() { setError(""); setLoading(true); try { const result = await signIn("credentials", { email, password, name, mode, redirect: false }); if (!result || result.error) throw new Error(result?.error || "Authentication failed"); toast.success(mode === "signup" ? "Welcome to Tender Trimesters" : "Welcome back, mama"); onOpenChange(false); setTimeout(() => window.location.reload(), 200); } catch (e: unknown) { const err = e as Error; setError(err.message || "Something went wrong"); } finally { setLoading(false); } }
  return (<Dialog open={open} onOpenChange={(v) => { onOpenChange(v); if (!v) { setError(""); setName(""); setEmail(""); setPassword(""); } }}><DialogContent className="rounded-2xl max-w-md" style={{ background: "#FFFEFC", border: "1px solid #E5E0D8" }}><DialogHeader><DialogTitle style={{ fontFamily: "var(--font-cormorant)" }} className="text-xl text-sage-deep">{mode === "signup" ? "Create your account" : "Welcome back, mama"}</DialogTitle><DialogDescription>{mode === "signup" ? "Free forever." : "Sign in to continue."}</DialogDescription></DialogHeader><div className="space-y-3 mt-2">{mode === "signup" && <div><Label htmlFor="au-name">Your name</Label><Input id="au-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Mama" className="mt-1 rounded-lg" /></div>}<div><Label htmlFor="au-email">Email</Label><Input id="au-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@email.com" className="mt-1 rounded-lg" /></div><div><Label htmlFor="au-pw">Password</Label><Input id="au-pw" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 6 characters" className="mt-1 rounded-lg" /></div>{error && <div className="text-[14px]" text-destructive bg-destructive/10 rounded-lg px-3 py-2">{error}</div>}<Button onClick={submit} disabled={loading} className="w-full rounded-full h-10 text-cream" style={{ background: "linear-gradient(135deg, #4A5D53, #2C3E36)" }}>{loading ? "One moment..." : mode === "signup" ? "Create account" : "Sign in"}</Button><div className="text-center text-[14px]" text-cocoa-soft">{mode === "signup" ? <>Already have an account? <button onClick={() => setMode("signin")} className="text-sage-deep hover:underline font-medium">Sign in</button></> : <>New here? <button onClick={() => setMode("signup")} className="text-sage-deep hover:underline font-medium">Create an account</button></>}</div></div></DialogContent></Dialog>);
}
